/**
 * Nhãn hiển thị của tag.
 *
 * Tag được LƯU dạng slug (`nen-tang`, `cau-truc-du-lieu`) vì nó là khoá lọc trên URL:
 * `/t/react?tag=hook`. Nhưng slug là thứ để máy đọc — người đọc thấy "nen-tang" thì
 * phải tự dịch ngược trong đầu, và với tiếng Việt thì dịch ngược là bất khả: từ
 * `nen-tang` không có cách nào suy ra "Nền tảng" thay vì "Nến tang" hay "Nên táng".
 *
 * Nên bảng dưới đây là BẮT BUỘC, không phải tiện nghi. Có một test kiểm mọi tag đang
 * dùng trong giáo trình đều có mặt ở đây — thêm tag mới vào `content/` mà quên khai
 * nhãn thì test đỏ, chứ không âm thầm hiện ra slug trên giao diện.
 *
 * Quy ước đặt nhãn:
 *  - Từ tiếng Việt  -> viết đủ dấu, viết hoa chữ đầu: `de-quy` -> "Đệ quy"
 *  - Thuật ngữ      -> giữ nguyên cách viết chuẩn của nó: `postgresql` -> "PostgreSQL",
 *                      `useeffect` -> "useEffect", `package-json` -> "package.json"
 *  - Không có hai tag nào chung một nhãn, nếu không dãy chip lọc sẽ có hai chip
 *    trông giống hệt nhau mà lọc ra hai kết quả khác nhau.
 */

const NHAN: Record<string, string> = {
  '1-1': 'Họp 1-1',
  '12-factor': '12-Factor',
  abac: 'ABAC',
  acid: 'ACID',
  adr: 'ADR',
  aggregate: 'Hàm tổng hợp',
  aggregation: 'Aggregation',
  api: 'API',
  'api-design': 'Thiết kế API',
  'app-router': 'App Router',
  async: 'Async',
  asyncio: 'asyncio',
  auth: 'Xác thực',
  'bang-bam': 'Bảng băm',
  'bao-cao': 'Báo cáo',
  'bao-dong': 'Báo động',
  'bao-mat': 'Bảo mật',
  bash: 'Bash',
  'bat-bien': 'Bất biến',
  'bat-dong-bo': 'Bất đồng bộ',
  bfs: 'BFS',
  bien: 'Biến',
  'bien-dich': 'Biên dịch',
  'big-o': 'Big-O',
  bisect: 'Bisect',
  bit: 'Bit',
  'bo-nho': 'Bộ nhớ',
  bson: 'BSON',
  cache: 'Cache',
  caching: 'Caching',
  canary: 'Canary',
  'cap-nhat': 'Cập nhật',
  'cau-hinh': 'Cấu hình',
  'cau-truc-du-lieu': 'Cấu trúc dữ liệu',
  cay: 'Cây',
  'chat-luong': 'Chất lượng',
  'cherry-pick': 'Cherry-pick',
  'chi-phi': 'Chi phí',
  'chiu-loi': 'Chịu lỗi',
  'chuan-hoa': 'Chuẩn hoá',
  chuoi: 'Chuỗi',
  ci: 'CI',
  'ci-cd': 'CI/CD',
  'circuit-breaker': 'Circuit breaker',
  class: 'Class',
  'clean-code': 'Clean code',
  closure: 'Closure',
  cloud: 'Cloud',
  'co-ban': 'Cơ bản',
  'code-review': 'Review code',
  cohesion: 'Kết dính',
  compose: 'Compose',
  comprehension: 'Comprehension',
  'computer-science': 'Khoa học máy tính',
  conflict: 'Xung đột',
  container: 'Container',
  context: 'Context',
  'context-manager': 'Context manager',
  cookie: 'Cookie',
  'core-web-vitals': 'Core Web Vitals',
  coupling: 'Liên kết',
  csrf: 'CSRF',
  cte: 'CTE',
  'cu-phap': 'Cú pháp',
  'cua-so-truot': 'Cửa sổ trượt',
  'custom-hook': 'Custom hook',
  'dan-dat': 'Dẫn dắt',
  'danh-doi': 'Đánh đổi',
  'danh-sach-lien-ket': 'Danh sách liên kết',
  'dat-ten': 'Đặt tên',
  'data-fetching': 'Tải dữ liệu',
  database: 'Database',
  dataclass: 'Dataclass',
  ddl: 'DDL',
  'de-quy': 'Đệ quy',
  dem: 'Đếm',
  dependency: 'Phụ thuộc',
  deploy: 'Deploy',
  'design-pattern': 'Design pattern',
  devops: 'DevOps',
  dfs: 'DFS',
  dns: 'DNS',
  'do-phuc-tap': 'Độ phức tạp',
  'do-thi': 'Đồ thị',
  docker: 'Docker',
  dockerfile: 'Dockerfile',
  'dong-thoi': 'Đồng thời',
  dry: 'DRY',
  'du-lieu': 'Dữ liệu',
  e2e: 'E2E',
  email: 'Email',
  encoding: 'Encoding',
  erd: 'ERD',
  'error-boundary': 'Error boundary',
  'error-budget': 'Error budget',
  'error-handling': 'Xử lý lỗi',
  'event-loop': 'Event loop',
  exception: 'Exception',
  explain: 'EXPLAIN',
  'feature-flag': 'Feature flag',
  file: 'File',
  finops: 'FinOps',
  float: 'Số thực',
  form: 'Form',
  frontend: 'Frontend',
  'full-text-search': 'Full-text search',
  functional: 'Lập trình hàm',
  generic: 'Generic',
  'giai-quyet-van-de': 'Giải quyết vấn đề',
  'giam-sat': 'Giám sát',
  'giao-thuc': 'Giao thức',
  'giao-tiep': 'Giao tiếp',
  git: 'Git',
  'github-actions': 'GitHub Actions',
  gitignore: '.gitignore',
  'go-loi': 'Gỡ lỗi',
  'group-by': 'GROUP BY',
  'hai-con-tro': 'Hai con trỏ',
  ham: 'Hàm',
  'hang-doi': 'Hàng đợi',
  hashing: 'Hashing',
  'he-dieu-hanh': 'Hệ điều hành',
  header: 'Header',
  heap: 'Heap',
  'hieu-nang': 'Hiệu năng',
  hook: 'Hook',
  http: 'HTTP',
  https: 'HTTPS',
  idempotency: 'Idempotency',
  idor: 'IDOR',
  index: 'Index',
  injection: 'Injection',
  'integration-test': 'Integration test',
  interface: 'Interface',
  io: 'I/O',
  isolation: 'Isolation',
  javascript: 'JavaScript',
  join: 'JOIN',
  jsonb: 'JSONB',
  jsx: 'JSX',
  'ke-hoach': 'Kế hoạch',
  'ke-thua': 'Kế thừa',
  'ket-hop': 'Kết hợp',
  khoa: 'Khoá',
  'kiem-thu': 'Kiểm thử',
  'kien-truc': 'Kiến trúc',
  'kieu-du-lieu': 'Kiểu dữ liệu',
  'lap-lich': 'Lập lịch',
  'lich-su': 'Lịch sử',
  linux: 'Linux',
  'load-balancer': 'Load balancer',
  'load-test': 'Kiểm thử tải',
  log: 'Log',
  logging: 'Logging',
  luong: 'Luồng',
  'ma-hoa': 'Mã hoá',
  mang: 'Mảng',
  map: 'Map',
  'mat-khau': 'Mật khẩu',
  'mau-thiet-ke': 'Mẫu thiết kế',
  memo: 'Memo',
  merge: 'Merge',
  method: 'Method',
  metric: 'Metric',
  microservices: 'Microservices',
  middleware: 'Middleware',
  migration: 'Migration',
  'mo-hinh': 'Mô hình',
  'mo-hinh-du-lieu': 'Mô hình dữ liệu',
  'mo-rong': 'Mở rộng',
  mock: 'Mock',
  module: 'Module',
  'moi-truong': 'Môi trường',
  'moi-truong-phat-trien': 'Môi trường phát triển',
  mongodb: 'MongoDB',
  monolith: 'Monolith',
  mvcc: 'MVCC',
  mypy: 'mypy',
  nat: 'NAT',
  'nen-tang': 'Nền tảng',
  network: 'Mạng',
  nextjs: 'Next.js',
  'ngan-xep': 'Ngăn xếp',
  nginx: 'Nginx',
  'nguyen-ly': 'Nguyên lý',
  nhanh: 'Nhánh',
  'nhat-quan': 'Nhất quán',
  'no-ky-thuat': 'Nợ kỹ thuật',
  nodejs: 'Node.js',
  nosql: 'NoSQL',
  oauth: 'OAuth',
  object: 'Object',
  observability: 'Observability',
  oidc: 'OIDC',
  'on-call': 'On-call',
  onboarding: 'Onboarding',
  oop: 'OOP',
  owasp: 'OWASP',
  'package-json': 'package.json',
  paradigm: 'Paradigm',
  'pham-vi': 'Phạm vi',
  'phan-hoi': 'Phản hồi',
  'phan-quyen': 'Phân quyền',
  'phan-ra': 'Phân rã',
  'phan-trang': 'Phân trang',
  'phong-van': 'Phỏng vấn',
  pip: 'pip',
  postgresql: 'PostgreSQL',
  postmortem: 'Hậu kiểm',
  profiling: 'Profiling',
  promise: 'Promise',
  proxy: 'Proxy',
  'pull-request': 'Pull request',
  python: 'Python',
  'quay-lui': 'Quay lui',
  'quy-hoach-dong': 'Quy hoạch động',
  'quy-trinh': 'Quy trình',
  quyen: 'Quyền',
  'quyet-dinh': 'Quyết định',
  'race-condition': 'Race condition',
  'rang-buoc': 'Ràng buộc',
  'ranh-gioi': 'Ranh giới',
  'rate-limit': 'Rate limit',
  rbac: 'RBAC',
  react: 'React',
  rebase: 'Rebase',
  redis: 'Redis',
  refactor: 'Refactor',
  reflog: 'Reflog',
  release: 'Release',
  'replica-set': 'Replica set',
  replication: 'Replication',
  request: 'Request',
  response: 'Response',
  rest: 'REST',
  retry: 'Thử lại',
  revalidate: 'Revalidate',
  revert: 'Revert',
  routing: 'Routing',
  runtime: 'Runtime',
  'sao-luu': 'Sao lưu',
  'sap-xep': 'Sắp xếp',
  schema: 'Schema',
  script: 'Script',
  secret: 'Secret',
  select: 'SELECT',
  semver: 'SemVer',
  seo: 'SEO',
  'server-actions': 'Server Actions',
  'server-component': 'Server Component',
  session: 'Session',
  sharding: 'Sharding',
  shell: 'Shell',
  sli: 'SLI',
  slo: 'SLO',
  'so-hoc': 'Số học',
  solid: 'SOLID',
  sql: 'SQL',
  'sql-injection': 'SQL Injection',
  ssrf: 'SSRF',
  stack: 'Stack',
  staging: 'Staging',
  stash: 'Stash',
  state: 'State',
  'state-management': 'Quản lý state',
  stateless: 'Stateless',
  'status-code': 'Mã trạng thái',
  streaming: 'Streaming',
  stub: 'Stub',
  'su-co': 'Sự cố',
  subquery: 'Subquery',
  suspense: 'Suspense',
  swap: 'Swap',
  syscall: 'System call',
  systemd: 'systemd',
  'tac-dung-phu': 'Tác dụng phụ',
  tag: 'Tag',
  'tcp-ip': 'TCP/IP',
  tdd: 'TDD',
  'ten-mien': 'Tên miền',
  test: 'Test',
  testing: 'Testing',
  'thiet-ke': 'Thiết kế',
  'thiet-ke-he-thong': 'Thiết kế hệ thống',
  this: 'this',
  'thuat-toan': 'Thuật toán',
  'thuyet-phuc': 'Thuyết phục',
  'tien-trinh': 'Tiến trình',
  'tim-kiem-nhi-phan': 'Tìm kiếm nhị phân',
  timeout: 'Timeout',
  tls: 'TLS',
  'toan-ven': 'Toàn vẹn',
  token: 'Token',
  'tong-quan': 'Tổng quan',
  trace: 'Trace',
  'trang-thai': 'Trạng thái',
  transaction: 'Transaction',
  'trien-khai': 'Triển khai',
  'truu-tuong': 'Trừu tượng',
  'truy-van': 'Truy vấn',
  'tu-duy': 'Tư duy',
  'tuong-lua': 'Tường lửa',
  'type-guard': 'Type guard',
  'type-hint': 'Type hint',
  'type-system': 'Hệ thống kiểu',
  typescript: 'TypeScript',
  unicode: 'Unicode',
  'unit-test': 'Unit test',
  unknown: 'unknown',
  'uoc-luong': 'Ước lượng',
  url: 'URL',
  useeffect: 'useEffect',
  usestate: 'useState',
  'uy-quyen': 'Uỷ quyền',
  validation: 'Validation',
  'van-hanh': 'Vận hành',
  venv: 'venv',
  versioning: 'Versioning',
  viet: 'Viết',
  vitest: 'Vitest',
  volume: 'Volume',
  'vong-doi': 'Vòng đời',
  'web-vitals': 'Web Vitals',
  where: 'WHERE',
  worker: 'Worker',
  workflow: 'Workflow',
  worktree: 'Worktree',
  'xoa-mem': 'Xoá mềm',
  xss: 'XSS',
  yagni: 'YAGNI',
  zod: 'Zod',
}

/**
 * Slug -> nhãn hiển thị.
 *
 * Tag lạ (người dùng tự thêm qua form sửa bài) không có trong bảng thì thay dấu gạch
 * bằng khoảng trắng và viết hoa chữ đầu. Cách này KHÔNG khôi phục được dấu tiếng Việt —
 * đó là lý do mọi tag của giáo trình phải nằm trong bảng, và có test canh việc đó.
 */
export function nhanTag(tag: string): string {
  const co = NHAN[tag]
  if (co !== undefined) return co
  const thay = tag.replace(/-/g, ' ')
  return thay.charAt(0).toUpperCase() + thay.slice(1)
}

/** Dùng cho test: danh sách tag đã khai nhãn. */
export function tagDaKhaiNhan(): string[] {
  return Object.keys(NHAN)
}
